#ifndef CHESS_PLAYER_MAP_H
#define CHESS_PLAYER_MAP_H
#include "map.h"

typedef int PlayerId;
typedef double PlayerLevel;

typedef enum {
    PLAYER_OUT_OF_MEMORY,
    PLAYER_NULL_ARGUMENT,
    PLAYER_INVALID_ID,
    PLAYER_INVALID_LOCATION,
    PLAYER_INVALID_MAX_GAMES,
    PLAYER_TOURNAMENT_ALREADY_EXISTS,
    PLAYER_TOURNAMENT_NOT_EXIST,
    PLAYER_GAME_ALREADY_EXISTS,
    PLAYER_INVALID_PLAY_TIME,
    PLAYER_EXCEEDED_GAMES,
    PLAYER_PLAYER_NOT_EXIST,
    PLAYER_TOURNAMENT_ENDED,
    PLAYER_NO_TOURNAMENTS_ENDED,
    PLAYER_NO_GAMES,
    PLAYER_SAVE_FAILURE,
    PLAYER_SUCCESS
} PlayerResult ;



Map playerCreateMap();
void playerDestroyMap(Map player_map);







#endif //CHESS_PLAYER_MAP_H
